api/urls.py
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.urls import path
from . import views
from .views import MyTokenObtainPairView, MyTokenObtainPairView2, MyTokenObtainPairView3, MyTokenObtainPairSerializer,show, add_property, PropertyCreateApi,EditProperty,EditFlatProp, CurrentUserView, managers_list,UserManager,UserLandlord, TenantList, tenants_list_manager, AddAccountCreateApi, AssignAccountCreateApi, AddExpensesCreateApi,ApproveExpenseAPIView, AccountView, ExpensesView,ExpensesFlatView,ManagerExpensesView, ManagerProperty, AddDocumentCreateApi, LandlordDocumentCreateApi, LandlordTenantDocCreateApi, ManagerFiles, ManagerDocumentCreateApi, ManagerDocumentView,TenantMyFilesCreateApi, TenantDocument, TenantFiles,TenantDocdelete, LandlordTenantFiles,LandlordTenantMyFiles,LandlordManagerMyFiles,LandlordManagerFiles, TenantPaymentUpdate, TenantDetails,TenantPaymentView, MakePaymentView,PaySalaryView,ViewSalary,LandlordViewSalary,ApproveSalary, ViewPayment,ViewTenantPayment, PageView, ManagerProp, LandlordProperty,ApprovePayment, AllProperties,PropertyNoManager, TenantViewLandlord, AssignedAccList, TestView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

        path('login/landlord', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('login/manager', MyTokenObtainPairView2.as_view(), name='token_obtain_pair2'),
    path('login/tenant', MyTokenObtainPairView3.as_view(), name='token_obtain_pair3'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('display', views.show, name='show'),
    path('home', views.home, name="home-web"),
    path('manager/web', views.manager_web, name='manager-web'),
    path('manager/detail/web', views.manager_detail_web, name='manager-detail-web'),
    path('property/detail/web', views.property_detail_web, name='property-detail-web'),
    path('property/web', views.property_web, name='property-web'),
    path('add', views.add_property),
    path('all-properties', AllProperties.as_view()),
    path('property/no-manager', PropertyNoManager.as_view()),
    path('edit-property/<int:id>', EditProperty.as_view()),
    path('edit-flat-property/<int:id>', EditFlatProp.as_view()),
    path('get-property/<int:id>', views.property_detail),
    path('get-property/<int:id>/flats', views.flat_detail),
    path('add-property', PropertyCreateApi.as_view(), name='add'),
    path('user-details', CurrentUserView.as_view(), name='user'),
    path('managers', views.managers_list),
    path('manager',UserManager.as_view()),
    path('landlord/profile',UserLandlord.as_view()),
    path('tenants', TenantList.as_view()),
    path('tenants/manager', views.tenants_list_manager),
    path('tenant/manager', TenantViewLandlord.as_view()),
    path('add-account', AddAccountCreateApi.as_view()),
    path('assign-account', AssignAccountCreateApi.as_view()),
    path('add-expenses', AddExpensesCreateApi.as_view()),
    path('account-list', AccountView.as_view()),
    path('expenses', ExpensesView.as_view()),
    path('expenses/flat/<int:id>',ExpensesFlatView.as_view()),
    path('expenses/<int:pk>/approve', ApproveExpenseAPIView.as_view(), name='approve-expense'),
    path('expenses/manager/<int:id>',ManagerExpensesView.as_view()),
    path('manager-property/<int:id>', ManagerProperty.as_view()),
    path('tenant/add-document', AddDocumentCreateApi.as_view()),
    path('tenant/my-files', TenantDocument.as_view()),
    path('tenant-myfiles/delete/<int:id>', TenantDocdelete.as_view()),
    path('tenant-payment', TenantPaymentUpdate.as_view()),
    path('tenant/details', TenantDetails.as_view()),
    path('make-payment', MakePaymentView.as_view()),
    path('pay-salary', PaySalaryView.as_view()),
    path('manager/salary-payments', ViewSalary.as_view()),
    path('landlord/salary-payments/<int:id>', LandlordViewSalary.as_view()),
    path('approve-salary/payment/<int:id>', ApproveSalary.as_view()),
    path('landlord/add-manager-doc', LandlordDocumentCreateApi.as_view()),
    path('manager-files', ManagerFiles.as_view()),
    path('manager/add-document', ManagerDocumentCreateApi.as_view()),
    path('landlord/add-tenant-doc', LandlordTenantDocCreateApi.as_view()),
    path('manager/my-files', ManagerDocumentView.as_view()),
    path('tenant/add-document', TenantMyFilesCreateApi.as_view()),
    path('tenant-files', TenantFiles.as_view()),
    path('landlord/tenant-files/<int:id>', LandlordTenantMyFiles.as_view()),
    path('landlord/manager-files/<int:id>', LandlordManagerMyFiles.as_view()),
    path('landlord/files/manager/<int:id>', LandlordManagerFiles.as_view()),
    path('landlord/files/tenant/<int:id>', LandlordTenantFiles.as_view()),
    path('tenant/view-payment', TenantPaymentView.as_view()),
    path('view-payment', ViewPayment.as_view()),
    path('view-payment/<int:id>', ViewTenantPayment.as_view()),
    path('page', PageView.as_view()),
    path('manager-prop', TestView.as_view()),
    path('landlord-property/<int:id>', LandlordProperty.as_view()),
    path('approve-payment/<int:id>', ApprovePayment.as_view()),
    path('assigned/accounts', AssignedAccList.as_view()),
    path('test', TestView.as_view())
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('webapp.urls')),
    path('accounts/password-reset', include('django_rest_passwordreset.urls', namespace='password_reset')),
]

api/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
# Create your models here.
payment_type = (
    ('online payment', 'online_payment'),
    ('transfer', 'transfer')
)
payment_option = (
    ('one-off', 'one-off'),
    ('recurring', 'recurring'),
    ('refundable', 'refundable')
)



class Flat(models.Model):
    name = models.CharField(max_length=100)
    number_of_rooms = models.PositiveIntegerField(null=True, blank=True)
    number_of_living_rooms = models.PositiveIntegerField(null=True, blank=True)
    number_of_kitchens = models.PositiveIntegerField(null=True, blank=True)
    number_of_toilets = models.PositiveIntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    test_id = models.IntegerField(null=True, blank=True)
    current_tenant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='active_tenant')
    all_tenants = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='tenant_list')
    vacant = models.BooleanField(null=True, blank=True, default=True)

    def __str__(self):
        return str(self.name)


class Property(models.Model):
    property_image = models.ImageField(blank=True, null=True, upload_to='uploads/properties')
    property_name = models.CharField(max_length=100, unique=True)
    address = models.TextField()
    flats = models.ManyToManyField(Flat,blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    all_managers = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='manager_list')
    manager_vacant = models.BooleanField(null=True, blank=True, default=True)
    


    def __str__(self):
        return str(self.property_name)
        
        
class AddPayment(models.Model):
    name = models.CharField(max_length=100)
    amount = models.PositiveIntegerField()
    type = models.CharField(max_length=100, choices=payment_option, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    termination_date = models.DateField(null=True, blank=True)
    tenant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    property = models.ForeignKey(Property, on_delete=models.CASCADE,null=True, blank=True)
    def __str__(self):
        return str(self.name)
        

class AddAccount(models.Model):
    account_name = models.CharField(max_length=100)
    bank_name = models.CharField(max_length=100)
    account_number = models.PositiveIntegerField()
    comment = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.account_name)

class AssignAccount(models.Model):
    account = models.ForeignKey(AddAccount, related_name='Assignaccount', on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    flats = models.ManyToManyField(Flat)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return str(self.account)


class AddExpenses(models.Model):
    amount = models.PositiveIntegerField()
    description = models.TextField()
    house = models.ForeignKey(Property, on_delete=models.CASCADE)
    flat_id = models.ForeignKey(Flat, on_delete=models.CASCADE, null=True, blank=True)
    receipt = models.FileField(upload_to='documents/')
    tenant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name="tenant_id")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(auto_now_add=True)
    approved_date = models.DateField(null=True, blank=True)
    approved_status = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.house)
        

class AddDocument(models.Model):
    name = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/tenant-documents')
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return str(self.name)
        
class MakePayment(models.Model):
    description = models.TextField()
    amount = models.PositiveIntegerField()
    type = models.CharField(max_length=100, choices=payment_type)
    ref_code = models.CharField(max_length=100, null=True, blank=True, unique=True)
    receipt = models.FileField(upload_to='documents/tenant-payments', null=True, blank=True)
    tenant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    status = models.BooleanField(default=False, null=True, blank=True)
    property = models.ForeignKey(Property, on_delete=models.CASCADE,null=True, blank=True)
    payment_date_and_time = models.DateTimeField(auto_now_add=True)
    approved_date = models.DateField(auto_now_add=False, auto_now=True)
    approved_by = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return self.description
        
class PaySalary(models.Model):
    description = models.TextField()
    amount = models.PositiveIntegerField()
    type = models.CharField(max_length=100, choices=payment_type)
    ref_code = models.CharField(max_length=100, null=True, blank=True, unique=True)
    receipt = models.FileField(upload_to='documents/salary-payments', null=True, blank=True)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name='user_manager')
    status = models.BooleanField(default=True, null=True, blank=True)
    manager_verify= models.BooleanField(default=False, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    payment_date_and_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description
    
class LandlordDocument(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    document = models.FileField(upload_to='documents/landlord-documents')
    date = models.DateField(auto_now_add=True)
    house_id = models.ForeignKey(Property, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name='manager_docs')
    
    def __str__(self):
        return str(self.name)
        
class ManagerDocument(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    document = models.FileField(upload_to='documents/manager-documents')
    date = models.DateField(auto_now_add=True)
    house_id = models.ForeignKey(Property, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return str(self.name)
    
class LandlordTenantDoc(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    document = models.FileField(upload_to='documents/landlord-documents')
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    tenant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name='tenant_docs')
    
    def __str__(self):
        return str(self.name)

templates/add_property.html
{% extends 'base.html' %}

{% block content %}
  <h1>{% if property.id %}Update{% else %}Create{% endif %} Property</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      {{ form.property_image.label_tag }}
      {{ form.property_image }}
    </div>
    <div class="form-group">
      {{ form.property_name.label_tag }}
      {{ form.property_name }}
    </div>
    <div class="form-group">
      {{ form.address.label_tag }}
      {{ form.address }}
    </div>
    <div class="form-group">
      {{ form.flats.label_tag }}
      <br>
      <a href="#" data-toggle="modal" data-target="#add-flat-modal">Add Flat</a>
      {{ form.flats.errors }}
    </div>
    <div class="form-group">
      {{ form.user.label_tag }}
      {{ form.user }}
    </div>
    <div class="form-group">
      {{ form.all_managers.label_tag }}
      {{ form.all_managers }}
    </div>
    <div class="form-group">
      {{ form.manager_vacant.label_tag }}
      {{ form.manager_vacant }}
    </div>
    <button type="submit" class="btn btn-primary">{% if property.id %}Update{% else %}Create{% endif %}</button>
  </form>

  <!-- Modal for adding a new flat -->
  <div class="modal fade" id="add-flat-modal" tabindex="-1" role="dialog" aria-labelledby="add-flat-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="add-flat-modal-label">Add Flat</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="post" id="add-flat-form">
          {% csrf_token %}
          <div class="modal-body">
            {{ flat_form.as_p }}
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script>
    $(document).ready(function() {
      $('#add-flat-form').submit(function(event) {
        event.preventDefault();
        var form = $(this);
        var url = form.attr('action');
        var formData = form.serialize();
        $.ajax({
          url: url,
          type: 'post',
          data: formData,
          success: function(data) {
            $('#id_flats').append('<option value="' + data.id + '" selected>' + data.name + '</option>');
            $('#add-flat-modal').modal('hide');
          },
          error: function(xhr, status, error) {
            $('#add-flat-form .modal-body').html(xhr.responseText);
          }
        });
      });
    });
  </script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


{% endblock content %}


templates/analytics.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <script src="{% static 'js/chartjs.min.js' %}"></script>
    <script type="text/javascript">
    var ctx = document.getElementById("chart-bars").getContext("2d");

    new Chart(ctx, {
      type: "bar",
      data: {
        labels: ["M", "T", "W", "T", "F", "S", "S"],
        datasets: [{
          label: "Sales",
          tension: 0.4,
          borderWidth: 0,
          borderRadius: 4,
          borderSkipped: false,
          backgroundColor: "rgba(255, 255, 255, .8)",
          data: [50, 20, 10, 22, 50, 10, 40],
          maxBarThickness: 6
        }, ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false,
          }
        },
        interaction: {
          intersect: false,
          mode: 'index',
        },
        scales: {
          y: {
            grid: {
              drawBorder: false,
              display: true,
              drawOnChartArea: true,
              drawTicks: false,
              borderDash: [5, 5],
              color: 'rgba(255, 255, 255, .2)'
            },
            ticks: {
              suggestedMin: 0,
              suggestedMax: 500,
              beginAtZero: true,
              padding: 10,
              font: {
                size: 14,
                weight: 300,
                family: "Roboto",
                style: 'normal',
                lineHeight: 2
              },
              color: "#fff"
            },
          },
          x: {
            grid: {
              drawBorder: false,
              display: true,
              drawOnChartArea: true,
              drawTicks: false,
              borderDash: [5, 5],
              color: 'rgba(255, 255, 255, .2)'
            },
            ticks: {
              display: true,
              color: '#f8f9fa',
              padding: 10,
              font: {
                size: 14,
                weight: 300,
                family: "Roboto",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
        },
      },
    });


    var ctx2 = document.getElementById("chart-line").getContext("2d");

    new Chart(ctx2, {
      type: "line",
      data: {
        labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        datasets: [{
          label: "Mobile apps",
          tension: 0,
          borderWidth: 0,
          pointRadius: 5,
          pointBackgroundColor: "rgba(255, 255, 255, .8)",
          pointBorderColor: "transparent",
          borderColor: "rgba(255, 255, 255, .8)",
          borderColor: "rgba(255, 255, 255, .8)",
          borderWidth: 4,
          backgroundColor: "transparent",
          fill: true,
          data: [50, 40, 300, 320, 500, 350, 200, 230, 500],
          maxBarThickness: 6

        }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false,
          }
        },
        interaction: {
          intersect: false,
          mode: 'index',
        },
        scales: {
          y: {
            grid: {
              drawBorder: false,
              display: true,
              drawOnChartArea: true,
              drawTicks: false,
              borderDash: [5, 5],
              color: 'rgba(255, 255, 255, .2)'
            },
            ticks: {
              display: true,
              color: '#f8f9fa',
              padding: 10,
              font: {
                size: 14,
                weight: 300,
                family: "Roboto",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
          x: {
            grid: {
              drawBorder: false,
              display: false,
              drawOnChartArea: false,
              drawTicks: false,
              borderDash: [5, 5]
            },
            ticks: {
              display: true,
              color: '#f8f9fa',
              padding: 10,
              font: {
                size: 14,
                weight: 300,
                family: "Roboto",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
        },
      },
    });

    var ctx3 = document.getElementById("chart-line-tasks").getContext("2d");

    new Chart(ctx3, {
      type: "line",
      data: {
        labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        datasets: [{
          label: "Mobile apps",
          tension: 0,
          borderWidth: 0,
          pointRadius: 5,
          pointBackgroundColor: "rgba(255, 255, 255, .8)",
          pointBorderColor: "transparent",
          borderColor: "rgba(255, 255, 255, .8)",
          borderWidth: 4,
          backgroundColor: "transparent",
          fill: true,
          data: [50, 40, 300, 220, 500, 250, 400, 230, 500],
          maxBarThickness: 6

        }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false,
          }
        },
        interaction: {
          intersect: false,
          mode: 'index',
        },
        scales: {
          y: {
            grid: {
              drawBorder: false,
              display: true,
              drawOnChartArea: true,
              drawTicks: false,
              borderDash: [5, 5],
              color: 'rgba(255, 255, 255, .2)'
            },
            ticks: {
              display: true,
              padding: 10,
              color: '#f8f9fa',
              font: {
                size: 14,
                weight: 300,
                family: "Roboto",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
          x: {
            grid: {
              drawBorder: false,
              display: false,
              drawOnChartArea: false,
              drawTicks: false,
              borderDash: [5, 5]
            },
            ticks: {
              display: true,
              color: '#f8f9fa',
              padding: 10,
              font: {
                size: 14,
                weight: 300,
                family: "Roboto",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
        },
      },
    });
  </script>
        
    
</head>

<div class="container-fluid py-2">
      <div class="row mt-4">
        <div class="col-lg-4 col-md-6 mt-4 mb-4">
          <div class="card z-index-2 ">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
              <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                <div class="chart">
                  <canvas id="chart-bars" class="chart-canvas" height="170"></canvas>
                </div>
              </div>
            </div>
            <div class="card-body">
              <h6 class="mb-0 ">Total Revenue</h6>
              <p class="text-sm ">Sales perfomance review</p>
              <hr class="dark horizontal">
              <div class="d-flex ">
                <i class="material-icons text-sm my-auto me-1">schedule</i>
                <p class="mb-0 text-sm"> 1 day ago </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 mt-4 mb-4">
          <div class="card z-index-2  ">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
              <div class="bg-gradient-success shadow-success border-radius-lg py-3 pe-1">
                <div class="chart">
                  <canvas id="chart-line" class="chart-canvas" height="170"></canvas>
                </div>
              </div>
            </div>
            <div class="card-body">
              <h6 class="mb-0 "> Total Expense </h6>
              <p class="text-sm "> <span class="font-weight-bolder"></span> Total amount spent</p>
              <hr class="dark horizontal">
              <div class="d-flex ">
                <i class="material-icons text-sm my-auto me-1">schedule</i>
                <p class="mb-0 text-sm"> 5 minutes ago </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 mt-4 mb-3">
          <div class="card z-index-2 ">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
              <div class="bg-gradient-dark shadow-dark border-radius-lg py-3 pe-1">
                <div class="chart">
                  <canvas id="chart-line-tasks" class="chart-canvas" height="170"></canvas>
                </div>
              </div>
            </div>
            <div class="card-body">
              <h6 class="mb-0 ">Ocupancy rate</h6>
              <p class="text-sm "></p>
              <hr class="dark horizontal">
              <div class="d-flex ">
                <i class="material-icons text-sm my-auto me-1">schedule</i>
                <p class="mb-0 text-sm">just updated</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="col-lg-4 mt-4 mb-3">
          <div class="card z-index-2 ">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
              <div class="bg-gradient-dark shadow-dark border-radius-lg py-3 pe-1">
                <div class="chart">
                  <canvas id="chart-line-tasks" class="chart-canvas" height="170"></canvas>
                </div>
              </div>
            </div>
            <div class="card-body">
              <h6 class="mb-0 ">Tenant Turnover Rate</h6>
              <p class="text-sm "></p>
              <hr class="dark horizontal">
              <div class="d-flex ">
                <i class="material-icons text-sm my-auto me-1">schedule</i>
                <p class="mb-0 text-sm">just updated</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      </div>
      </div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
      

{% endblock content %}

templates/flat_create.html
{% extends 'base.html' %}

{% block content %}
<head>
    <style>
        .custom-form {
  /* Add custom styles for the form container */
  /* Example styles */
  margin: 20px;
  padding: 20px;
  border: 1px solid #ccc;
  background-color: #f8f8f8;
}

.custom-form .form-group {
  /* Add custom styles for the form groups */
  /* Example styles */
  margin-bottom: 15px;
}

.custom-form .form-label {
  /* Add custom styles for the form labels */
  /* Example styles */
  font-weight: bold;
}

.custom-form input[type="text"],
.custom-form input[type="number"] {
  /* Add custom styles for the form input fields */
  /* Example styles */
  width: 100%;
  padding: 5px;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.custom-form button[type="submit"] {
  /* Add custom styles for the submit button */
  /* Example styles */
  padding: 10px 20px;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

/* Add additional custom styles as needed */

    </style>
</head>


  <form method="POST" action="" class="custom-form">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="{{ form.name.id_for_label }}" class="form-label">Name</label>
      {{ form.name }}
    </div>
    
    <div class="form-group">
      <label for="{{ form.number_of_rooms.id_for_label }}" class="form-label">Number of Rooms</label>
      {{ form.number_of_rooms }}
    </div>
    
    <div class="form-group">
      <label for="{{ form.number_of_living_rooms.id_for_label }}" class="form-label">Number of Living Rooms</label>
      {{ form.number_of_living_rooms }}
    </div>
    
    <div class="form-group">
      <label for="{{ form.number_of_kitchens.id_for_label }}" class="form-label">Number of Kitchens</label>
      {{ form.number_of_kitchens }}
    </div>
    
    <div class="form-group">
      <label for="{{ form.number_of_toilets.id_for_label }}" class="form-label">Number of Toilets</label>
      {{ form.number_of_toilets }}
    </div>
    
    <div class="form-group">
      <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
      {{ form.description }}
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

